const constants = {
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",

    LOGOUT: "LOGOUT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL_USERNAME: "LOGIN_FAIL_USERNAME",
    LOGIN_FAIL_PASSWORD: "LOGIN_FAIL_PASSWORD",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    GET_TEAMS: "GET_TEAMS"
}

export default constants